[project]
version = "0.3.0"
requires-python = "==3.9"
dependencies = [
    "numpy",
    "torch",
    "opencv-python",
    "loguru",
    "tqdm",
    "torchvision",
    "thop",
    "ninja",
    "tabulate",
    "psutil",
    "tensorboard",
    "pycocotools==2.0.2",
    "onnx",
    "onnx-simplifier",
]

[build-system]
requires = [
    "setuptools>=40.8.0",
    "wheel",
    "torch==2.8.0",
    "ninja",
    "pycocotools"
]
build-backend = "setuptools.build_meta"
