[build-system]
requires = [
    "setuptools>=40.8.0",
    "wheel",
    "torch",
    "ninja",
]
build-backend = "setuptools.build_meta"

[project]
name = "yolox"
dynamic = ["version"]
authors = [ { name = "megvii basedet team" } ]
readme = "README.md"
requires-python = ">=3.6"
license = { text = "Apache Software License" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "numpy",
    "torch",
    "opencv-python",
    "loguru",
    "tqdm",
    "torchvision",
    "thop",
    "ninja",
    "tabulate",
    "psutil",
    "tensorboard",
    "pycocotools==2.0.2",
    "onnx",
    "onnx-simplifier",
]

[project.urls]
"Homepage" = "https://github.com/Megvii-BaseDetection/YOLOX"
"Documentation" = "https://yolox.readthedocs.io"
"Source" = "https://github.com/Megvii-BaseDetection/YOLOX"
"Tracker" = "https://github.com/Megvii-BaseDetection/YOLOX/issues"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = { attr = "yolox.__version__" }